# Generated by Django 5.0.3 on 2024-04-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeProdApp', '0003_alter_productionuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoreport',
            name='photo',
        ),
        migrations.AddField(
            model_name='photoreport',
            name='image',
            field=models.ImageField(default=None, upload_to='report_photos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
