# Generated by Django 5.0.3 on 2024-04-12 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeProdApp', '0004_remove_photoreport_photo_photoreport_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
