# Generated by Django 5.0.6 on 2024-06-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeProdApp', '0006_productionzone_responsible_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('production_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeProdApp.productionzone')),
            ],
        ),
    ]
